
server:
  port : 9050

spring:
  application:
    name: inventory-microservice
  profiles:
    include: rmq
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver 
  rabbitmq:
    host: localhost 
    port: 5673
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

multitenancy:
    type: schema
    default-tenant: microservices
entity:
  packages: com.barath.app.inventory

order:
   request:
      queue: order-request-queue   
   response:
      queue : order-response-queue      

cancel:
  order:
    queue: cancel-order-queue
   


dead:
    letter:
        queue:
            name: deadLetterQueue

exchange:
  name : order-to-inventory
  
